chunks_relative_path: chunks_single_par.jsonl
splade_embds_relative_path: splade_doc_embs_single_par.pt
retriever_topk: 100
reranker_topk: 100
expand_query: true
retriever: splade
rerank: true
reranker: openai_embeds
run: ollama
llm_model: "llama3.1:8b-instruct"